apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres-component
  template:
    metadata:
      labels:
        component: postgres-component
    spec:
      securityContext:
        fsGroup: 999
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
      # initContainers:
      #   - name: init-permissions
      #     image: busybox
      #     command: ['sh', '-c', 'chown -R 999:999 /var/lib/postgresql/data']
      #     securityContext:
      #       runAsUser: 0  # Run as root
      #     volumeMounts:
      #       - name: postgres-storage
      #         mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpasswordsecret
                  key: PGPASSWORD
          # securityContext:
          #   runAsUser: 999
          #   runAsGroup: 999
